package com.sms.cloud.services.storage;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "messages")
public class Message {

    private String id;
    private String messageContent;
    private String fromAddress;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getMessageContent() {
        return messageContent;
    }

    @DynamoDBAttribute
    public String getFromAddress() {
        return fromAddress;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public void setFromAddress(String address) {
        fromAddress = address;
    }

    public void setId(String id) {
        this.id = id;
    }

}
